spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_project?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat, wall,log4j2
  mvc:
    static-path-pattern: /static/**
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#  resources:
#    static-locations: classpath:/static
